# Generated by Django 5.1.1 on 2024-09-30 14:58

import django.db.models.deletion
from django.db import migrations, models

import car.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("brand", "0001_initial"),
        ("model", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price",
                    models.IntegerField(
                        validators=[car.validators.validate_price]
                    ),
                ),
                (
                    "mileage",
                    models.IntegerField(
                        validators=[car.validators.validate_mileage]
                    ),
                ),
                ("exterior_color", models.CharField(max_length=50)),
                ("interior_color", models.CharField(max_length=50)),
                ("fuel_type", models.CharField(max_length=50)),
                (
                    "transmission",
                    models.CharField(
                        choices=[
                            ("Manual", "Manual"),
                            ("Automatic", "Automatic"),
                            ("CVT", "CVT"),
                        ],
                        default="Manual",
                        max_length=50,
                    ),
                ),
                ("engine", models.CharField(max_length=50)),
                ("on_sale", models.BooleanField()),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="brand.brand",
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="model.model",
                    ),
                ),
            ],
            options={
                "verbose_name": "car",
                "verbose_name_plural": "cars",
                "ordering": ["price"],
            },
        ),
    ]
