# Generated by Django 5.1.1 on 2024-09-30 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("car", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="car",
            old_name="on_sale",
            new_name="is_on_sale",
        ),
    ]
