# Generated by Django 5.1.1 on 2024-09-30 14:58

from django.db import migrations, models

import model.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Model",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "issue_year",
                    models.IntegerField(
                        validators=[model.validators.validate_year]
                    ),
                ),
                ("body_style", models.CharField(max_length=60)),
            ],
            options={
                "verbose_name": "model",
                "verbose_name_plural": "models",
                "ordering": ["name"],
            },
        ),
    ]
